# report_content.py
# ============================================================
# ZENTRALE CONTENT-DATEI – Single Source of Truth
# Alle Texte, Typen, Funktionsnamen, Meaning Cards hier.
# Wird importiert von: report_builder.py, pdf_report.py, app.py
# Wird als JSON injiziert in: results.html
# ============================================================

from typing import Dict, List, Any

# ============================================================
# 11 PERFORMANCE-FUNKTIONEN: IDs -> Klartext-Namen
# ============================================================
FUNCTION_NAMES: Dict[str, str] = {
    "DST": "Leistungsmodus unter Belastung",
    "STR": "Entscheidungsstabilität & Ordnung",
    "MAC": "Verantwortungs- & Einflussorientierung",
    "KON": "Soziale Steuerung & Anschlussfähigkeit",
    "MOR": "Werte-Stabilität & innere Entscheidungsgrenzen",
    "IND": "Autonomie- & Gestaltungsmodus",
    "AKT": "Energie- & Handlungsdynamik",
    "INF": "Verarbeitungs- & Entscheidungsmodus",
    "COM": "Vergleichs- & Leistungsreferenz",
    "AUF": "Sichtbarkeits- & Feedbackabhängigkeit",
    "STA": "Positions- & Anerkennungsorientierung",
}

# Reihenfolge für PDF / Bar Chart
FUNCTION_ORDER: List[str] = [
    "DST", "STR", "MAC", "KON", "MOR",
    "IND", "AKT", "INF", "COM", "AUF", "STA"
]

# ============================================================
# 5 PERFORMANCE-PROFIL-TYPEN (Arbeitsmodi)
# ============================================================
TYPE_MAP: Dict[str, Dict[str, str]] = {
    "A": {
        "name": "Stabilitätsmodus",
        "label": "Fundament-Performer",
        "hint": "Du lieferst, wenn Rahmen & Standards klar sind.",
        "explain": "Ruhig, zuverlässig, präzise. Führung: klare Rahmen, keine künstliche Hektik.",
        "headline": "Ich bleibe klar, wenn andere wackeln.",
    },
    "B": {
        "name": "Druckmodus",
        "label": "Peak-Performer",
        "hint": "Je höher der Druck, desto besser – wenn du ihn steuerst.",
        "explain": "Hochfokussiert in kritischen Momenten. Führung: Druck dosieren + klare Regeln + Regeneration.",
        "headline": "Je höher der Druck, desto besser werde ich – wenn ich ihn steuere.",
    },
    "C": {
        "name": "Gestaltungsmodus",
        "label": "Lösungs- & Konzeptmodus",
        "hint": "Freiheit erzeugt Leistung. Ziele ja – Detailsteuerung nein.",
        "explain": "Kreativ, konzeptionell, lösungsorientiert. Führung: Ziel klar, Weg offen. Ergebnis zählt, nicht die Methode.",
        "headline": "Ich brauche Freiheit, um Leistung zu bringen.",
    },
    "D": {
        "name": "Vergleichsmodus",
        "label": "Ambitions-Performer",
        "hint": "Leistung entsteht im Wettbewerb, Standards und Feedback.",
        "explain": "Leistungsgetrieben, maßstabsorientiert, ambitioniert. Führung: Maßstäbe sauber setzen, Feedback sachlich, Vergleich kontrollieren.",
        "headline": "Leistung entsteht für mich im Wettbewerb.",
    },
    "E": {
        "name": "Kontrollmodus",
        "label": "Steuerungs-Performer",
        "hint": "Du performst maximal, wenn Verantwortung klar bei dir liegt.",
        "explain": "Übernimmt Verantwortung, denkt steuernd, behält Überblick. Führung: Verantwortung abgrenzen, Abgeben trainieren.",
        "headline": "Ich übernehme Verantwortung – und behalte den Überblick.",
    },
}

# ============================================================
# MEANING CARDS (Web-Ergebnis + PDF Seite 4)
# Top-Hebel / Reibungszone / Steuerung – kurz & knackig
# ============================================================
MEANING_CARDS: Dict[str, Dict[str, str]] = {
    "DST": {
        "top":   "Du kannst unter Druck Leistung abrufen, Prioritäten setzen und handlungsfähig bleiben – das ist ein echter Leistungshebel, wenn es zählt.",
        "low":   "Wenn der Druck steigt, sinkt dein Zugriff: Fokus bricht weg, Entscheidungen werden schwerer, du gehst in Vermeidung – Leistung wird unberechenbar.",
        "steer": "Lege vor jeder Druckphase maximal 3 Prioritäten fest. Plane nach jeder Belastung einen festen Reset ein (Bewegung, Luft, Pause). Im Druck: nur die nächste klare Handlung – nicht das große Ganze.",
    },
    "STR": {
        "top":   "Klare Ordnung stabilisiert dich: Abläufe, Prioritäten und Zuständigkeiten geben dir Ruhe – du bleibst sauber und zuverlässig, auch wenn es unruhig wird.",
        "low":   "Ohne Struktur verlierst du unnötig Leistung: Chaos, Unklarheit und wechselnde Prioritäten kosten Energie und erhöhen deine Fehlerquote.",
        "steer": "Schreibe jeden Morgen deine 3 wichtigsten Aufgaben auf – nicht mehr. Lege schriftlich fest, wer was entscheidet und bis wann. Starte und beende jeden Tag mit dem gleichen Ablauf.",
    },
    "MAC": {
        "top":   "Du nimmst Verantwortung und Einfluss aktiv – du gehst voran, entscheidest, steuerst. Das ist ein Führungshebel in jedem Leistungssystem.",
        "low":   "Du wartest eher auf Vorgaben: Verantwortung bleibt unklar, Einfluss wird verschenkt – dadurch entstehen Verzögerung, Unklarheit und weniger Eigenverantwortung.",
        "steer": "Schreibe auf: Wofür bin ich zuständig – und wofür nicht? Lege fest, welche Entscheidungen du selbst triffst, ohne zu fragen. Schließe jeden Tag eine Sache bewusst ab, statt sie liegen zu lassen.",
    },
    "KON": {
        "top":   "Austausch und Rückmeldung erhöhen deine Leistung: du wirst klarer, stabiler und abrufbarer durch Gespräche und gemeinsames Denken.",
        "low":   "Ohne sozialen Anschluss kippt deine Leistung schneller: du ziehst dich zurück, verlierst Rückmeldung und Energie – Entscheidungen werden enger.",
        "steer": "Plane einen festen Gesprächstermin pro Woche mit einer Person, deren Meinung dich weiterbringt. Geh mit konkreten Fragen rein, nicht mit offenem Reden. Höre nur auf Feedback von Menschen, die selbst Ergebnisse liefern.",
    },
    "MOR": {
        "top":   "Werte geben dir innere Ruhe und Richtung: du entscheidest klarer, wenn es zu deinen Grundsätzen passt – Integrität wird zur Leistungskraft.",
        "low":   "Wertekonflikte kosten Leistung: innere Unruhe, Grübeln oder widersprüchliche Entscheidungen – Energie geht in den Konflikt statt in die Umsetzung.",
        "steer": "Schreibe 3 Werte auf, die für dich nicht verhandelbar sind – und 3 Dinge, die du auf keinen Fall tust. Wenn eine Situation inneren Widerstand auslöst: sofort benennen, nicht verdrängen.",
    },
    "IND": {
        "top":   "Freiheit erzeugt Leistung: wenn du gestalten darfst, lieferst du kreative Lösungen, Eigenständigkeit und starke Ergebnisse.",
        "low":   "Zu wenig Freiraum drückt deine Leistung: du wirst passiver, wartest eher ab oder arbeitest nur das Nötigste ab statt wirklich etwas zu bewegen.",
        "steer": "Kläre mit deinem Umfeld: Was ist das Ziel? Der Weg dorthin bleibt deiner. Schreibe auf, woran man erkennt, dass du fertig bist – damit Freiheit nicht in Beliebigkeit kippt. Setze dir ein Zeitfenster, in dem du ungestört gestalten kannst.",
    },
    "AKT": {
        "top":   "Tempo ist dein Motor: du kommst ins Tun, erzeugst Schwung und ziehst Umsetzung durch – Klarheit entsteht bei dir oft erst durch Handlung.",
        "low":   "Wenn Schwung fehlt, wird es zäh: du bleibst zu lange im Kopf, wartest ab oder kommst schwer in die Umsetzung – Leistung startet zu spät.",
        "steer": "Starte jede Aufgabe mit dem kleinstmöglichen Schritt – innerhalb von 5 Minuten, ohne Diskussion. Liefere erst eine erste Version, dann verbessere. Setze dir bewusst ein Zeitlimit: Wann fängst du an, wann hörst du auf?",
    },
    "INF": {
        "top":   "Du lieferst über Verständnis: wenn du Zusammenhänge siehst, triffst du bessere Entscheidungen und bleibst stabil – auch unter Druck.",
        "low":   "Bei zu wenig Klarheit wirst du unsicher: du zögerst, entscheidest aus dem Bauch oder drehst dich im Kreis – Risiko: Fehlentscheidungen oder endloses Abwägen.",
        "steer": "Lege vor jeder Entscheidung fest: Welche 2–3 Informationen brauche ich mindestens? Nicht mehr sammeln. Gib dir ein Zeitfenster: Bis wann muss die Entscheidung stehen? Frage dich vorher: Was wäre der schlimmste Fehler – und wie verhindere ich ihn?",
    },
    "COM": {
        "top":   "Wettbewerb und Vergleich schärfen dich: du hebst deine Standards, erhöhst die Intensität und gehst in den Leistungsmodus, wenn es messbar wird.",
        "low":   "Ohne Vergleich fehlt dir der äußere Antrieb: du bleibst eher im Komfortbereich, Standards werden weicher, Leistung verliert an Schärfe.",
        "steer": "Wähle einen einzigen Maßstab, an dem du dich misst – nicht zehn. Nutze Vergleich nur phasenweise, nicht dauerhaft. Mache deinen Fortschritt sichtbar: Führe eine einfache Liste, die zeigt, wo du letzte Woche standest und wo du jetzt stehst.",
    },
    "AUF": {
        "top":   "Feedback und Sichtbarkeit stabilisieren deine Leistung: du ziehst Energie aus Rückmeldung und kannst dadurch konsequent abrufen.",
        "low":   "Ohne Rückmeldung verlierst du die Orientierung: du wirst unsichtbar, holst dir keine Korrektur und deine Leistung wird weniger zielgenau.",
        "steer": "Fordere einmal pro Woche aktiv Rückmeldung ein – von einer konkreten Person zu einem konkreten Thema. Halte deine Ergebnisse kurz schriftlich fest (3 Sätze reichen). Trenne klar: Feedback ist eine Information über dein Ergebnis – kein Urteil über deinen Wert.",
    },
    "STA": {
        "top":   "Rolle und Position setzen Energie frei: wenn deine Stellung klar ist, zeigst du Leistung sichtbarer und mit mehr Anspruch.",
        "low":   "Wenn deine Rolle unklar ist, entsteht Reibung: du nimmst zu wenig Raum ein, bleibst unsichtbar – und deine Leistung wird nicht abgerufen.",
        "steer": "Schreibe in einem Satz auf, wofür du verantwortlich bist – und sage diesen Satz laut. Mache deinen Beitrag sichtbar: Was hast du diese Woche konkret geliefert? Nutze deine Position, um Orientierung zu geben – nicht um dein Ego zu bedienen.",
    },
}

# ============================================================
# KATEGORIE-TEXTE (PDF: pro Funktion eine Doppelseite)
# Struktur: title, worum, hoch, mittel, niedrig, praxis, merksatz
# ============================================================
CATEGORY_TEXT: Dict[str, Dict[str, Any]] = {
    "DST": {
        "title": "LEISTUNGSMODUS UNTER BELASTUNG",
        "worum": [
            "Diese Funktion entscheidet nicht, wie leistungsfähig du sein könntest –",
            "sondern ob du Leistung abrufst, wenn es wirklich zählt.",
            "",
            "Zeitdruck.",
            "Erwartung.",
            "Bewertung.",
            "Risiko.",
            "",
            "Genau dort trennt sich Vorbereitung von Leistung.",
            "",
            "Der Leistungsmodus unter Belastung beschreibt, wie dein System reagiert,",
            "wenn die äußeren Bedingungen enger werden –",
            "und ob du dann klarer wirst oder enger.",
            "",
            "Nicht im Training.",
            "Nicht im Kopf.",
            "Sondern im Moment der Entscheidung.",
        ],
        "hoch": [
            "Druck aktiviert dich.",
            "Er macht dich klarer, nicht hektischer.",
            "Du bleibst handlungsfähig, während andere anfangen zu zweifeln.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du setzt schneller Prioritäten",
            "• Du triffst Entscheidungen auch ohne vollständige Sicherheit",
            "• Du hältst den Fokus, während andere Tempo verlieren",
            "• Du kannst Leistung nicht nur vorbereiten, sondern im entscheidenden Moment abrufen",
            "",
            "Das ist ein echter Leistungshebel.",
            "Denn genau hier entstehen Führung, Klarheit und Verlässlichkeit.",
            "",
            "Wichtig:",
            "Diese Stärke wirkt nicht automatisch –",
            "sie wirkt dann am stärksten, wenn du Druck bewusst steuerst",
            "und nicht dauerhaft im Hochlastmodus bleibst.",
        ],
        "mittel": [
            "Leistung ist unter Druck möglich, aber nicht stabil.",
            "Manche Situationen treiben dich an – andere überrollen dich.",
            "",
            "Typisch:",
            "• Zu viel gleichzeitig",
            "• Tempoverlust bei Unklarheit",
            "• Wechsel zwischen blindem Aktionismus und Blockade",
            "",
            "Der Schlüssel hier ist nicht mehr Disziplin,",
            "sondern bessere Drucksteuerung.",
        ],
        "niedrig": [
            "Steigender Druck senkt deinen Zugriff.",
            "Entscheidungen werden schwerer, nicht klarer.",
            "Leistung wird unberechenbar – genau dann, wenn sie gebraucht wird.",
            "",
            "Nicht, weil Kompetenz fehlt.",
            "Sondern weil dein System Schutz sucht, statt Ergebnisse zu liefern.",
        ],
        "praxis": [
            "Vor jeder Druckphase: Schreibe maximal 3 Prioritäten auf einen Zettel. Nicht mehr. Druck braucht Richtung, keine endlose Aufgabenliste.",
            "Nach jeder Belastung: Mache einen bewussten Schnitt – aufstehen, Luft holen, kurz bewegen. Kein Grübeln, kein Handy. Das ist kein Luxus, das ist Leistungserhalt.",
            "Im Druck selbst: Frage dich nur eine Sache – Was ist jetzt der nächste saubere Schritt? Nicht das große Ganze. Nur der nächste Schritt."
        ],
        "merksatz": "Leistung unter Druck ist kein Talent. Sie ist das Ergebnis von klarer Richtung, bewusster Steuerung und der Fähigkeit, im entscheidenden Moment zu handeln.",
    },
    "STR": {
        "title": "ENTSCHEIDUNGSSTABILITÄT & ORDNUNG",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du intelligent bist –",
            "sondern ob du in Unruhe sauber entscheiden kannst.",
            "",
            "Unklarheit.",
            "Zu viele Baustellen.",
            "Wechselnde Prioritäten.",
            "",
            "Hier verlieren viele nicht wegen fehlender Kompetenz –",
            "sondern weil ihnen ein System fehlt.",
            "",
            "Entscheidungsstabilität & Ordnung beschreibt,",
            "ob Struktur dich stabilisiert –",
            "oder ob Chaos dir unbemerkt Leistung abzieht.",
        ],
        "hoch": [
            "Struktur beruhigt dich nicht nur – sie macht dich gefährlich effizient.",
            "Du bleibst klar, weil du Ordnung in Entscheidungen bringst.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du setzt Prioritäten sauber statt hektisch",
            "• Du triffst Entscheidungen nach klaren Maßstäben – nicht nach Stimmung",
            "• Du arbeitest stabil, auch wenn außen Lärm ist",
            "• Du verlierst wenig Energie an Durcheinander",
            "",
            "Das ist ein Elitehebel.",
            "Denn Struktur ist nicht Ordnungsliebe –",
            "Struktur ist Zugriff auf Leistung.",
        ],
        "mittel": [
            "Du kannst strukturiert sein – aber nicht dauerhaft.",
            "Manchmal läuft es über klare Abläufe.",
            "Manchmal frisst dich die Unordnung.",
            "",
            "Typisch:",
            "• Du startest stark – verlierst aber die Richtung",
            "• Du wechselst zu oft die Priorität",
            "• Du bist im Kopf organisiert – aber nicht im Alltag",
            "",
            "Der Schlüssel ist nicht mehr Druck,",
            "sondern ein fester Ablauf, der jeden Tag greift.",
        ],
        "niedrig": [
            "Durcheinander kostet dich unnötig Leistung.",
            "Nicht dramatisch – aber ständig.",
            "",
            "Typisch:",
            "• Entscheidungen dauern zu lange",
            "• Umsetzung beginnt zu spät",
            "• Energie geht ins Sortieren statt ins Liefern",
            "",
            "Nicht, weil du schwach bist.",
            "Sondern weil du ohne Ordnung zu viel im Kopf tragen musst.",
        ],
        "praxis": [
            "Jeden Morgen: Schreibe 3 Aufgaben auf, die heute erledigt werden. Nicht fünf, nicht zehn. Drei. Wenn alles wichtig ist, ist nichts klar.",
            "Zuständigkeiten festlegen: Schreibe auf, wer welche Entscheidung trifft und bis wann. Jede Unklarheit hier kostet dich Leistung.",
            "Fester Start, fester Abschluss: Beginne jeden Arbeitstag mit dem gleichen Ablauf und beende ihn mit einer kurzen Rückschau. Ordnung entsteht nicht von allein."
        ],
        "merksatz": "Struktur ist kein Selbstzweck. Sie ist das, was deine Leistung auch dann stabil hält, wenn um dich herum alles wackelt.",
    },
    "MAC": {
        "title": "VERANTWORTUNGS- & EINFLUSSORIENTIERUNG",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du motiviert bist –",
            "sondern ob du Verantwortung übernimmst, wenn Richtung fehlt.",
            "",
            "Verantwortung heißt:",
            "nicht warten, bis jemand entscheidet.",
            "Sondern die Entscheidung selbst führen.",
            "",
            "Diese Kategorie zeigt,",
            "ob Einfluss dich aktiviert –",
            "oder ob du lieber im Ausführen bleibst.",
        ],
        "hoch": [
            "Verantwortung setzt bei dir Energie frei.",
            "Du willst steuern, gestalten, entscheiden.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du übernimmst Verantwortung statt Ausreden",
            "• Du triffst Entscheidungen, wenn andere noch diskutieren",
            "• Du willst Wirkung – nicht nur Beschäftigung",
            "• Du hältst Systeme stabil, weil du Verantwortung trägst",
            "",
            "Das ist Führung in Reinform.",
            "Nicht die Position – sondern das Verhalten.",
        ],
        "mittel": [
            "Du kannst Verantwortung übernehmen – aber nicht immer automatisch.",
            "Manchmal gehst du voran.",
            "Manchmal wartest du auf klare Ansagen.",
            "",
            "Typisch:",
            "• Du übernimmst, wenn du dich sicher fühlst",
            "• Du zögerst, wenn dein Zuständigkeitsbereich unklar ist",
            "• Du lässt Entscheidungen liegen, wenn niemand sie dir zuweist",
            "",
            "Der Schlüssel ist eine klare Festlegung –",
            "damit du nicht in Unklarheit hängen bleibst.",
        ],
        "niedrig": [
            "Eigenverantwortung ist nicht dein stärkster Antrieb.",
            "Du wartest eher auf Vorgaben oder klare Führung.",
            "",
            "Typisch:",
            "• Du lieferst gut – aber du steuerst wenig",
            "• Entscheidungen bleiben in der Luft",
            "• Einfluss wird verschenkt",
            "",
            "Nicht, weil dir Stärke fehlt.",
            "Sondern weil Verantwortung nicht sauber bei dir landet.",
        ],
        "praxis": [
            "Zuständigkeit aufschreiben: Was ist mein Bereich – und was nicht? Ohne klare Abgrenzung bleibt Verantwortung schwammig.",
            "Entscheidungsrahmen festlegen: Schreibe auf, welche Entscheidungen du ab sofort selbst triffst, ohne nachzufragen. Zum Beispiel: „Alles unter Betrag X entscheide ich allein."",
            "Jeden Tag eine Sache abschließen: Nicht aufschieben, nicht parken. Eine offene Aufgabe bewusst zu Ende bringen – das trainiert Eigenverantwortung."
        ],
        "merksatz": "Einfluss ist kein Titel. Einfluss ist die Fähigkeit, Verantwortung zu übernehmen, bevor es jemand von dir verlangt.",
    },
    "KON": {
        "title": "SOZIALE STEUERUNG & ANSCHLUSSFÄHIGKEIT",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du gesellig bist –",
            "sondern ob Kontakt deine Leistung verstärkt oder verwässert.",
            "",
            "Rückmeldung.",
            "Gemeinsames Denken.",
            "Teamdynamik.",
            "",
            "Hier entsteht entweder Klarheit –",
            "oder Ablenkung.",
            "",
            "Diese Kategorie zeigt,",
            "ob du über Austausch stabiler wirst –",
            "oder ob du allein am stärksten bist.",
        ],
        "hoch": [
            "Kontakt ist bei dir kein Smalltalk.",
            "Kontakt ist Leistung.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Gespräche machen dich klarer",
            "• Rückmeldung stabilisiert deinen Fokus",
            "• Du wirst besser durch gemeinsames Denken",
            "• Du ziehst Energie aus einem starken Umfeld",
            "",
            "Das ist ein starker Hebel –",
            "wenn du ihn bewusst nutzt und nicht jedem Impuls die Führung gibst.",
        ],
        "mittel": [
            "Du kannst über Austausch wachsen – aber nicht immer.",
            "Manchmal macht Kontakt dich stärker.",
            "Manchmal kostet er dich Fokus.",
            "",
            "Typisch:",
            "• Du holst Rückmeldung, aber zu unstrukturiert",
            "• Du bist offen, aber manchmal zu leicht beeinflussbar",
            "• Du wechselst zwischen Rückzug und zu viel Austausch",
            "",
            "Der Schlüssel ist, die Häufigkeit deines Austauschs bewusst zu steuern –",
            "nicht nach Gefühl.",
        ],
        "niedrig": [
            "Du bist sehr eigenständig.",
            "Du brauchst wenig Kontakt, um zu liefern.",
            "",
            "Das kann Stärke sein –",
            "das Risiko ist Vereinzelung.",
            "",
            "Typisch:",
            "• Du holst zu wenig Korrektur",
            "• Du bleibst unsichtbar, obwohl du Leistung bringst",
            "• Du trägst zu viel allein mit dir herum",
        ],
        "praxis": [
            "Ein fester Termin pro Woche: Verabrede dich mit einer Person, deren Meinung dich fordert. Geh mit 2 konkreten Fragen rein – kein offenes Plaudern.",
            "Rückmeldung filtern: Höre nur auf Menschen, die selbst Ergebnisse liefern. Nicht jede Meinung verdient deine Aufmerksamkeit.",
            "Austausch als Werkzeug nutzen: Gespräche sind dann wertvoll, wenn sie Klarheit bringen – nicht wenn sie deine Entscheidung ersetzen."
        ],
        "merksatz": "Kontakt ist dann ein Hebel, wenn er Klarheit erzeugt – nicht wenn er deine Entscheidung ersetzt.",
    },
    "MOR": {
        "title": "WERTE-STABILITÄT & INNERE ENTSCHEIDUNGSGRENZEN",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du ein guter Mensch bist –",
            "sondern ob du unter Druck eine klare innere Linie hast.",
            "",
            "Werte sind keine Worte.",
            "Werte sind Grenzen.",
            "",
            "Diese Kategorie zeigt,",
            "ob du mit Integrität ruhiger wirst –",
            "oder ob innere Konflikte dir Leistung entziehen.",
        ],
        "hoch": [
            "Du entscheidest klarer, wenn Dinge zu deinen Grundsätzen passen.",
            "Du verlierst weniger Energie an innere Diskussion.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du hast eine klare Linie",
            "• Du kannst Nein sagen ohne Drama",
            "• Du bleibst stabil, weil du weißt wofür du stehst",
            "• Integrität macht dich leistungsfähig",
            "",
            "Das ist ein Elitevorteil –",
            "weil du unter Druck weniger inneren Lärm hast.",
        ],
        "mittel": [
            "Du hast Werte – aber sie sind nicht immer scharf geführt.",
            "Manchmal bist du klar.",
            "Manchmal bist du zu anpassungsfähig.",
            "",
            "Typisch:",
            "• Du passt dich an, auch wenn es dich innerlich etwas kostet",
            "• Du rechtfertigst Entscheidungen zu lange",
            "• Du spürst Unruhe, aber benennst sie nicht",
            "",
            "Der Schlüssel ist Klarheit: Was geht auf keinen Fall – und warum?",
        ],
        "niedrig": [
            "Anpassungsfähigkeit ist hoch – aber Grenzen sind weich.",
            "Das kann Flexibilität sein –",
            "das Risiko ist Beliebigkeit.",
            "",
            "Typisch:",
            "• Innere Unruhe bei Entscheidungen",
            "• Du verlierst Energie ans Grübeln",
            "• Du driftest, wenn Druck kommt",
        ],
        "praxis": [
            "Werte aufschreiben: 3 Grundsätze, die für dich nicht verhandelbar sind. Und 3 Dinge, die du auf keinen Fall tust. Kurz. Hart. Ohne Erklärung.",
            "Konflikte sofort benennen: Wenn etwas gegen deine Linie läuft, sprich es innerhalb von 24 Stunden an. Nicht wegdrücken, nicht warten.",
            "Entscheidungen sauber treffen: Weniger erklären, mehr klar sein. Wenn du weißt, wofür du stehst, brauchst du weniger Rechtfertigung."
        ],
        "merksatz": "Werte sind keine Dekoration. Werte sind das, was dich unter Druck stabil hält, wenn alles andere wackelt.",
    },
    "IND": {
        "title": "AUTONOMIE- & GESTALTUNGSMODUS",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du freiheitsliebend bist –",
            "sondern ob Freiheit bei dir Leistung freisetzt oder Fokus zerstört.",
            "",
            "Manche liefern mit Struktur.",
            "Andere liefern mit Spielraum.",
            "",
            "Diese Kategorie zeigt,",
            "ob du über Gestaltungsfreiheit besser wirst –",
            "oder ob du über klare Führung stabiler bist.",
        ],
        "hoch": [
            "Freiheit macht dich nicht chaotisch –",
            "Freiheit macht dich produktiv.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du entwickelst Lösungen statt nur Schritte abzuarbeiten",
            "• Du lieferst besser ohne Detailsteuerung von außen",
            "• Du denkst in Möglichkeiten statt in Vorgaben",
            "• Du findest eigene Wege, ohne das Ziel aus den Augen zu verlieren",
            "",
            "Das ist ein starker Hebel –",
            "wenn Ziel und Ergebnis klar definiert sind.",
        ],
        "mittel": [
            "Du kannst mit Freiheit umgehen – aber nicht unbegrenzt.",
            "Zu wenig Spielraum bremst dich.",
            "Zu viel Spielraum zerstreut dich.",
            "",
            "Typisch:",
            "• Du brauchst Leitplanken, aber keine Detailsteuerung",
            "• Du lieferst, wenn Ziele klar sind",
            "• Du verlierst Fokus, wenn niemand das Ergebnis definiert",
        ],
        "niedrig": [
            "Du bist eher systemtreu.",
            "Du wirst besser, wenn Vorgaben klar sind.",
            "",
            "Risiko:",
            "Wenn niemand führt, wirst du passiver.",
            "Nicht aus Bequemlichkeit –",
            "sondern weil dir der Rahmen fehlt, der dir Zugriff gibt.",
        ],
        "praxis": [
            "Spielraum bewusst festlegen: Kläre mit deinem Umfeld – was ist das Ziel, was ist der Rahmen? Der Weg dorthin bleibt deiner. Aber das Ziel muss glasklar sein.",
            "Ergebnis definieren: Schreibe in einem Satz auf, woran man erkennt, dass du fertig bist. Ohne das wird Freiheit zur Endlosschleife.",
            "Gestaltungszeit einplanen: Blocke dir feste Zeitfenster, in denen du ungestört arbeiten und denken kannst. Freiheit braucht Raum – aber auch ein Ende."
        ],
        "merksatz": "Autonomie ist dann ein Hebel, wenn sie geführt ist: Ziel klar, Spielraum bewusst, Ergebnis messbar.",
    },
    "AKT": {
        "title": "ENERGIE- & HANDLUNGSDYNAMIK",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du fleißig bist –",
            "sondern ob du Zugriff über Handlung bekommst.",
            "",
            "Manche gewinnen Klarheit durch Denken.",
            "Andere gewinnen Klarheit durch Bewegung.",
            "",
            "Diese Kategorie zeigt,",
            "ob Tempo bei dir Schwung erzeugt –",
            "oder ob du eher über Ruhe stabil bleibst.",
        ],
        "hoch": [
            "Tempo ist bei dir kein Stress –",
            "Tempo ist dein Startknopf.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du kommst schnell ins Tun",
            "• Du baust Schwung auf",
            "• Du entscheidest oft besser in Bewegung",
            "• Du ziehst Dinge durch, statt sie zu zerdenken",
            "",
            "Das ist ein Leistungsvorteil –",
            "wenn du Gas geben und Bremsen bewusst steuerst.",
        ],
        "mittel": [
            "Du kannst Tempo machen – aber nicht immer stabil.",
            "Manchmal bist du schnell.",
            "Manchmal bleibst du hängen.",
            "",
            "Typisch:",
            "• Der Start fällt schwer, wenn die Aufgabe groß wirkt",
            "• Du bist gut im Sprint, aber ungleichmäßig im Rhythmus",
            "• Du wechselst zwischen blindem Aktionismus und Abwarten",
        ],
        "niedrig": [
            "Du bist nachdenklicher – und oft langsamer im Start.",
            "Das kann Qualität bringen.",
            "",
            "Risiko:",
            "Du kommst zu spät in die Umsetzung.",
            "Nicht, weil du nicht kannst –",
            "sondern weil du zu lange im Kopf bleibst.",
        ],
        "praxis": [
            "5-Minuten-Start: Nimm dir die Aufgabe vor und beginne sofort mit dem kleinstmöglichen Schritt. Nicht planen, nicht diskutieren – anfangen. Innerhalb von 5 Minuten.",
            "Erste Version liefern: Liefere erst ein Ergebnis, dann verbessere es. Schwung vor Perfektion. Die meisten Dinge werden besser, wenn sie erstmal existieren.",
            "Bewusst Gas geben und bremsen: Setze dir klare Zeitfenster – wann beschleunigst du, wann stoppst du? Tempo ohne Steuerung führt in die Erschöpfung."
        ],
        "merksatz": "Tempo ist ein Hebel – aber nur, wenn du es führst. Sonst führt es dich.",
    },
    "INF": {
        "title": "VERARBEITUNGS- & ENTSCHEIDUNGSMODUS",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du klug bist –",
            "sondern wie du Sicherheit für Entscheidungen erzeugst.",
            "",
            "Information kann Klarheit sein.",
            "Oder ein Versteck.",
            "",
            "Diese Kategorie zeigt,",
            "ob du über Verständnis stabil wirst –",
            "oder ob du schneller über dein Bauchgefühl handelst.",
        ],
        "hoch": [
            "Du wirst stabil, wenn du Zusammenhänge siehst.",
            "Du triffst bessere Entscheidungen, wenn die Lage klar ist.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du denkst strukturiert",
            "• Du erkennst Muster",
            "• Du triffst Entscheidungen fundiert",
            "• Du bleibst ruhiger, weil Fakten dir Zugriff geben",
            "",
            "Wichtig:",
            "Der Hebel kippt, wenn Analyse zur Verzögerung wird.",
        ],
        "mittel": [
            "Du brauchst etwas Klarheit – aber nicht alles.",
            "Manchmal analysierst du gut.",
            "Manchmal entscheidest du zu schnell oder zu spät.",
            "",
            "Typisch:",
            "• Du willst Sicherheit, aber verlierst dich gelegentlich",
            "• Du sammelst zu viel Information, wenn Druck steigt",
            "• Du entscheidest aus dem Bauch, wenn Daten fehlen",
        ],
        "niedrig": [
            "Du bist eher intuitiv.",
            "Du entscheidest schneller, auch ohne viele Daten.",
            "",
            "Das kann mutig und schnell sein –",
            "das Risiko sind Fehlentscheidungen oder blinde Flecken,",
            "wenn die nötige Grundlage fehlt.",
        ],
        "praxis": [
            "Vor jeder Entscheidung: Lege fest, welche 2–3 Informationen du mindestens brauchst. Nicht zwanzig. Dann entscheide.",
            "Zeitfenster setzen: Gib jeder Entscheidung eine Frist. Zum Beispiel: „Bis Freitag 12 Uhr steht meine Entscheidung." Ohne Frist analysierst du endlos.",
            "Schlimmsten Fall vordenken: Frage dich vor wichtigen Entscheidungen: Was wäre der größte Fehler – und wie verhindere ich ihn? Das gibt Sicherheit, ohne endlos zu grübeln."
        ],
        "merksatz": "Information ist dann eine Stärke, wenn sie zur Entscheidung führt – nicht wenn sie die Entscheidung ersetzt.",
    },
    "COM": {
        "title": "VERGLEICHS- & LEISTUNGSREFERENZ",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du ehrgeizig bist –",
            "sondern ob Vergleich dich schärft oder dich fremdsteuert.",
            "",
            "Vergleich kann Standards erhöhen.",
            "Oder Fokus zerstören.",
            "",
            "Diese Kategorie zeigt,",
            "wie stark Wettbewerb, Messbarkeit und äußere Maßstäbe",
            "deinen Leistungsmodus aktivieren.",
        ],
        "hoch": [
            "Vergleich schärft dich.",
            "Wenn es messbar wird, wirst du wach.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Deine Standards steigen, deine Intensität steigt",
            "• Du gehst in den Leistungsmodus, wenn es zählt",
            "• Du willst messen statt hoffen",
            "• Du lieferst stärker, wenn der Rahmen klar ist",
            "",
            "Wichtig:",
            "Vergleich ist ein Werkzeug – nicht dein Chef.",
        ],
        "mittel": [
            "Wettbewerb kann dich antreiben – aber nicht dauerhaft.",
            "Manchmal aktiviert er dich.",
            "Manchmal lenkt er dich ab.",
            "",
            "Typisch:",
            "• Du nutzt Maßstäbe, aber nicht gezielt",
            "• Du wirst phasenweise vom Vergleich getrieben",
            "• Du verlierst Fokus, wenn der Vergleich ungesund wird",
        ],
        "niedrig": [
            "Du bist weniger wettkampfgetrieben.",
            "Das kann Stabilität geben.",
            "",
            "Risiko:",
            "Zu wenig äußere Reibung.",
            "Standards bleiben weich.",
            "Dein Potenzial wird nicht voll herausgefordert.",
        ],
        "praxis": [
            "Einen Maßstab wählen: Suche dir eine einzige Messgröße, an der du deinen Fortschritt erkennst. Nicht zehn – eine. Zum Beispiel: Umsatz, Abschlussquote, Kundenzufriedenheit.",
            "Vergleich nur in Phasen nutzen: Schalte Wettbewerb gezielt ein – zum Beispiel in einem 4-Wochen-Sprint. Danach bewusst rausnehmen. Dauervergleich macht dich fremdgesteuert.",
            "Fortschritt sichtbar machen: Führe eine einfache Wochenliste – wo standest du letzte Woche, wo stehst du jetzt? Das zeigt Entwicklung, ohne dein Selbstbild an andere zu koppeln."
        ],
        "merksatz": "Vergleich ist dann wertvoll, wenn er deine Standards erhöht – ohne dich emotional zu steuern.",
    },
    "AUF": {
        "title": "SICHTBARKEITS- & FEEDBACKABHÄNGIGKEIT",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du Aufmerksamkeit magst –",
            "sondern ob Rückmeldung bei dir Zugriff erzeugt oder Druck erzeugt.",
            "",
            "Resonanz kann Leistung stabilisieren.",
            "Oder dich abhängig machen.",
            "",
            "Diese Kategorie zeigt,",
            "wie stark Rückmeldung, Sichtbarkeit und Bewertung",
            "deine Leistung beeinflussen.",
        ],
        "hoch": [
            "Rückmeldung ist bei dir Treibstoff.",
            "Resonanz aktiviert deine Einsatzbereitschaft.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du lieferst stärker, wenn Rückmeldung klar ist",
            "• Du ziehst Energie aus Sichtbarkeit",
            "• Du wirst konsequenter, wenn du gesehen wirst",
            "• Du reagierst empfindlich auf Bewertung",
            "",
            "Wichtig:",
            "Du musst Rückmeldung führen – sonst führt sie dich.",
        ],
        "mittel": [
            "Rückmeldung kann dich antreiben – aber du brauchst sie nicht immer.",
            "Manchmal ist sie nützlich.",
            "Manchmal lenkt sie ab.",
            "",
            "Typisch:",
            "• Du holst dir Rückmeldung, aber nicht gezielt",
            "• Du bist robust, aber manchmal getroffen",
            "• Du wirst ungleichmäßig, wenn Resonanz ausbleibt",
        ],
        "niedrig": [
            "Du bist unabhängiger.",
            "Du brauchst wenig Rückmeldung, um zu liefern.",
            "",
            "Das kann Stärke sein –",
            "das Risiko ist Unsichtbarkeit.",
            "Du bringst Leistung – aber sie wird nicht wahrgenommen, weil sie niemand sieht.",
        ],
        "praxis": [
            "Einmal pro Woche Rückmeldung einholen: Geh auf eine konkrete Person zu und frage gezielt: „Was lief gut, was kann besser?" Nicht hoffen, dass es jemand von selbst sagt.",
            "Ergebnisse festhalten: Schreibe am Ende jeder Woche in 3 Sätzen auf, was du geliefert hast. Das macht deine Leistung sichtbar – für dich und für andere.",
            "Rückmeldung von deinem Selbstwert trennen: Feedback sagt etwas über dein Ergebnis – nicht über deinen Wert als Mensch. Wer das trennen kann, wird durch Rückmeldung stärker statt verletzlicher."
        ],
        "merksatz": "Rückmeldung ist dann ein Hebel, wenn sie Klarheit erzeugt – nicht wenn sie deine Stabilität ersetzt.",
    },
    "STA": {
        "title": "POSITIONS- & ANERKENNUNGSORIENTIERUNG",
        "worum": [
            "Diese Funktion entscheidet nicht, ob du Status willst –",
            "sondern ob Rolle und Position dir Zugriff geben.",
            "",
            "Rolle kann Sicherheit sein.",
            "Oder Druck.",
            "",
            "Diese Kategorie zeigt,",
            "wie stark Anerkennung, Stellung und Rollenklarheit",
            "deine Leistung freisetzen oder begrenzen.",
        ],
        "hoch": [
            "Rolle aktiviert Leistung.",
            "Wenn deine Position klar ist, steigt dein Anspruch und deine Präsenz.",
            "",
            "Typische Wirkung bei hoher Ausprägung:",
            "• Du spielst stärker auf Niveau, wenn der Rahmen klar ist",
            "• Du übernimmst Raum, wenn du legitimiert bist",
            "• Du lieferst sichtbarer und konsequenter",
            "• Du reagierst empfindlich auf Rangordnungen",
            "",
            "Wichtig:",
            "Status muss funktional bleiben – nicht emotional.",
        ],
        "mittel": [
            "Rolle hilft – aber sie ist nicht alles.",
            "Manchmal brauchst du Klarheit im System.",
            "Manchmal bleibst du von innen heraus stabil.",
            "",
            "Typisch:",
            "• Du willst Anerkennung, aber nicht um jeden Preis",
            "• Du nimmst Raum, aber manchmal zu wenig",
            "• Du schwankst zwischen Sichtbarkeit und Rückzug",
        ],
        "niedrig": [
            "Du bist stärker von innen heraus angetrieben.",
            "Status ist kein großer Auslöser für dich.",
            "",
            "Risiko:",
            "Du bleibst zu unsichtbar.",
            "Nicht weil du klein bist –",
            "sondern weil du dir nicht genug Raum gibst, obwohl du Wirkung hättest.",
        ],
        "praxis": [
            "Rolle in einem Satz definieren: Schreibe auf: „Ich bin verantwortlich für …" – und sage diesen Satz laut. Klarheit über deine Rolle gibt dir sofort Zugriff.",
            "Deinen Beitrag sichtbar machen: Schreibe am Ende jeder Woche auf, was du konkret geliefert hast. Nicht um anzugeben – sondern damit deine Wirkung nicht untergeht.",
            "Position als Werkzeug nutzen: Nutze deine Stellung, um Orientierung zu geben und Erwartungen zu klären – nicht um dein Ego zu bedienen. Funktionale Sichtbarkeit schlägt Status jedes Mal."
        ],
        "merksatz": "Position ist dann ein Hebel, wenn sie deine Wirkung erhöht – nicht wenn sie dich steuert.",
    },
}

# ============================================================
# HELPER: Band-Einstufung (für PDF + Web)
# ============================================================
def get_band(pct: int) -> str:
    """Gibt 'niedrig', 'mittel' oder 'hoch' zurück."""
    if pct < 25:
        return "niedrig"
    if pct < 75:
        return "mittel"
    return "hoch"

def get_band_label(pct: int) -> str:
    """Gibt lesbares Band-Label mit Prozentbereich zurück."""
    b = get_band(pct)
    if b == "hoch":
        return "hoch (75–100 %)"
    if b == "mittel":
        return "mittel (25–75 %)"
    return "niedrig (0–25 %)"
